### ISSUE TITLE
Update for Windows.

### ISSUE THREAD

**Issue by UnDadFeated** [eclair4151/MinecraftUpdater#2]
Hello,

I can run the script on windows with windows python, but screen commands are not supported.

Is there any chance, you can update this to run won a windows machine?

Thank you.

**Comment by inputoutput1126** [comment]
No, because there's no easy way for the script to interact with the command prompt unless you run the server within python

**Comment by UnDadFeated** [comment]
Thank you for the response.

I have python running on this windows server. The script runs, it even downloaded the updated. Jar file of newest snapshot, but I do not know where the file went, and then the "screen" commands cause error in script.

**Comment by inputoutput1126** [comment]
Exactly. The problem is that python has no good way of interacting with the minecraft server to issue the shutdown command among, etc.

**Comment by UnDadFeated** [comment]
Is their a way to modify the script to simply update to latest snapshot when run, and skip the screen commands? Like I can schedule to run it at 3am every morning. So that way it would work in windows?

**Comment by inputoutput1126** [comment]
You could do that, the problem is your server will continue running the old version and will probably error out because the server.jar file is not the same.

**Comment by UnDadFeated** [comment]
So you would need a command to download update, then kill current server, remove old .jar, rename new .jar and execute it.

**Comment by swolewizard** [comment]
are you still interested in a working windows version, I updated this code for my personal use, but I can give you the code if you still want it

**Comment by UnDadFeated** [comment]
yes please, i run a small local server on my HTPC for the kids. I want it
to update automagically.

**Comment by swolewizard** [comment]
Here it is https://github.com/swolewizard/MinecraftUpdaterForWindows
Make sure you have a .bat in your server directory where updater.py is located, called 'Manual_run.bat' with

`@ECHO OFF`
`java -Xms16384M -Xmx16384M -jar minecraft_server.jar`
`pause`


Also make sure your server starts with a jar gui, it requires that to be open which is how it stops/starts the server

**Comment by UnDadFeated** [comment]
Thank you so much!

**Comment by UnDadFeated** [comment]
Works great!, I had to download JAVA 16 JDK and then was able to run the
GUI without the console popping up with javaw in the new jdk folder.
Everything works great!

**Comment by swolewizard** [comment]
Good to know I helped someone out 😄 
You might want to keep the console open with the GUI, I had it that way so when the GUI is force closed the console will still be open to save the world and end the server safely, but I never tried it without a console so keep an eye out for server roll backs / possibility of world corruption.
